// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptConnectionReducer from "../accept_connection_reducer";
import AcceptProjectInviteReducer from "../accept_project_invite_reducer";
import AddColleagueByIdentityReducer from "../add_colleague_by_identity_reducer";
import BlockCompanyReducer from "../block_company_reducer";
import CancelRequestReducer from "../cancel_request_reducer";
import ClearNotificationsReducer from "../clear_notifications_reducer";
import CreateAccountReducer from "../create_account_reducer";
import CreateCompanyReducer from "../create_company_reducer";
import CreateProjectReducer from "../create_project_reducer";
import DeclineConnectionReducer from "../decline_connection_reducer";
import DeclineProjectInviteReducer from "../decline_project_invite_reducer";
import DeleteCompanyReducer from "../delete_company_reducer";
import DeleteInviteCodeReducer from "../delete_invite_code_reducer";
import DeleteProjectReducer from "../delete_project_reducer";
import DisconnectCompanyReducer from "../disconnect_company_reducer";
import GenerateInviteCodeReducer from "../generate_invite_code_reducer";
import InviteToProjectReducer from "../invite_to_project_reducer";
import JoinCompanyReducer from "../join_company_reducer";
import KickFromProjectReducer from "../kick_from_project_reducer";
import LeaveCompanyReducer from "../leave_company_reducer";
import LeaveProjectReducer from "../leave_project_reducer";
import MarkAllNotificationsReadReducer from "../mark_all_notifications_read_reducer";
import MarkNotificationReadReducer from "../mark_notification_read_reducer";
import RemoveColleagueReducer from "../remove_colleague_reducer";
import RequestConnectionReducer from "../request_connection_reducer";
import SendConnectionChatReducer from "../send_connection_chat_reducer";
import SendProjectChatReducer from "../send_project_chat_reducer";
import SwitchActiveCompanyReducer from "../switch_active_company_reducer";
import TransferOwnershipReducer from "../transfer_ownership_reducer";
import UnblockCompanyReducer from "../unblock_company_reducer";
import UpdateCapabilitiesReducer from "../update_capabilities_reducer";
import UpdateCompanyProfileReducer from "../update_company_profile_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UpdateUserRoleReducer from "../update_user_role_reducer";

export type AcceptConnectionParams = __Infer<typeof AcceptConnectionReducer>;
export type AcceptProjectInviteParams = __Infer<typeof AcceptProjectInviteReducer>;
export type AddColleagueByIdentityParams = __Infer<typeof AddColleagueByIdentityReducer>;
export type BlockCompanyParams = __Infer<typeof BlockCompanyReducer>;
export type CancelRequestParams = __Infer<typeof CancelRequestReducer>;
export type ClearNotificationsParams = __Infer<typeof ClearNotificationsReducer>;
export type CreateAccountParams = __Infer<typeof CreateAccountReducer>;
export type CreateCompanyParams = __Infer<typeof CreateCompanyReducer>;
export type CreateProjectParams = __Infer<typeof CreateProjectReducer>;
export type DeclineConnectionParams = __Infer<typeof DeclineConnectionReducer>;
export type DeclineProjectInviteParams = __Infer<typeof DeclineProjectInviteReducer>;
export type DeleteCompanyParams = __Infer<typeof DeleteCompanyReducer>;
export type DeleteInviteCodeParams = __Infer<typeof DeleteInviteCodeReducer>;
export type DeleteProjectParams = __Infer<typeof DeleteProjectReducer>;
export type DisconnectCompanyParams = __Infer<typeof DisconnectCompanyReducer>;
export type GenerateInviteCodeParams = __Infer<typeof GenerateInviteCodeReducer>;
export type InviteToProjectParams = __Infer<typeof InviteToProjectReducer>;
export type JoinCompanyParams = __Infer<typeof JoinCompanyReducer>;
export type KickFromProjectParams = __Infer<typeof KickFromProjectReducer>;
export type LeaveCompanyParams = __Infer<typeof LeaveCompanyReducer>;
export type LeaveProjectParams = __Infer<typeof LeaveProjectReducer>;
export type MarkAllNotificationsReadParams = __Infer<typeof MarkAllNotificationsReadReducer>;
export type MarkNotificationReadParams = __Infer<typeof MarkNotificationReadReducer>;
export type RemoveColleagueParams = __Infer<typeof RemoveColleagueReducer>;
export type RequestConnectionParams = __Infer<typeof RequestConnectionReducer>;
export type SendConnectionChatParams = __Infer<typeof SendConnectionChatReducer>;
export type SendProjectChatParams = __Infer<typeof SendProjectChatReducer>;
export type SwitchActiveCompanyParams = __Infer<typeof SwitchActiveCompanyReducer>;
export type TransferOwnershipParams = __Infer<typeof TransferOwnershipReducer>;
export type UnblockCompanyParams = __Infer<typeof UnblockCompanyReducer>;
export type UpdateCapabilitiesParams = __Infer<typeof UpdateCapabilitiesReducer>;
export type UpdateCompanyProfileParams = __Infer<typeof UpdateCompanyProfileReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UpdateUserRoleParams = __Infer<typeof UpdateUserRoleReducer>;

