// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddColleagueByIdentityReducer from "../add_colleague_by_identity_reducer";
import CreateCompanyReducer from "../create_company_reducer";
import CreateUserProfileReducer from "../create_user_profile_reducer";
import DeleteInviteCodeReducer from "../delete_invite_code_reducer";
import GenerateInviteCodeReducer from "../generate_invite_code_reducer";
import JoinCompanyReducer from "../join_company_reducer";
import RemoveColleagueReducer from "../remove_colleague_reducer";
import TransferOwnershipReducer from "../transfer_ownership_reducer";
import UpdateCapabilitiesReducer from "../update_capabilities_reducer";
import UpdateCompanyProfileReducer from "../update_company_profile_reducer";
import UpdateUserRoleReducer from "../update_user_role_reducer";

export type AddColleagueByIdentityParams = __Infer<typeof AddColleagueByIdentityReducer>;
export type CreateCompanyParams = __Infer<typeof CreateCompanyReducer>;
export type CreateUserProfileParams = __Infer<typeof CreateUserProfileReducer>;
export type DeleteInviteCodeParams = __Infer<typeof DeleteInviteCodeReducer>;
export type GenerateInviteCodeParams = __Infer<typeof GenerateInviteCodeReducer>;
export type JoinCompanyParams = __Infer<typeof JoinCompanyReducer>;
export type RemoveColleagueParams = __Infer<typeof RemoveColleagueReducer>;
export type TransferOwnershipParams = __Infer<typeof TransferOwnershipReducer>;
export type UpdateCapabilitiesParams = __Infer<typeof UpdateCapabilitiesReducer>;
export type UpdateCompanyProfileParams = __Infer<typeof UpdateCompanyProfileReducer>;
export type UpdateUserRoleParams = __Infer<typeof UpdateUserRoleReducer>;

