// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  companyId: __t.u64().primaryKey().name("company_id"),
  canInstall: __t.bool().name("can_install"),
  hasCnc: __t.bool().name("has_cnc"),
  hasLargeFormat: __t.bool().name("has_large_format"),
  hasBucketTruck: __t.bool().name("has_bucket_truck"),
});
