// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ConnectionStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  companyA: __t.u64().name("company_a"),
  companyB: __t.u64().name("company_b"),
  get status() {
    return ConnectionStatus;
  },
  requestedBy: __t.identity().name("requested_by"),
  blockingCompanyId: __t.option(__t.u64()).name("blocking_company_id"),
  initialMessage: __t.string().name("initial_message"),
  createdAt: __t.timestamp().name("created_at"),
});
