// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  UserRole,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  companyId: __t.u64().name("company_id"),
  get role() {
    return UserRole;
  },
  joinedAt: __t.timestamp().name("joined_at"),
});
