// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NotificationType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  recipientIdentity: __t.identity().name("recipient_identity"),
  companyId: __t.u64().name("company_id"),
  get notificationType() {
    return NotificationType.name("notification_type");
  },
  title: __t.string(),
  body: __t.string(),
  isRead: __t.bool().name("is_read"),
  createdAt: __t.timestamp().name("created_at"),
});
