// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Person = __t.object("Person", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const User = __t.object("User", {
  identity: __t.identity(),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

