// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Capability = __t.object("Capability", {
  companyId: __t.u64(),
  canInstall: __t.bool(),
  hasCnc: __t.bool(),
  hasLargeFormat: __t.bool(),
  hasBucketTruck: __t.bool(),
});
export type Capability = __Infer<typeof Capability>;

export const Company = __t.object("Company", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  name: __t.string(),
  slug: __t.string(),
  location: __t.string(),
  bio: __t.string(),
  isPublic: __t.bool(),
});
export type Company = __Infer<typeof Company>;

export const InviteCode = __t.object("InviteCode", {
  code: __t.string(),
  companyId: __t.u64(),
  createdBy: __t.identity(),
  usesRemaining: __t.u32(),
});
export type InviteCode = __Infer<typeof InviteCode>;

export const OnlineUser = __t.object("OnlineUser", {
  identity: __t.identity(),
  online: __t.bool(),
});
export type OnlineUser = __Infer<typeof OnlineUser>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  companyId: __t.option(__t.u64()),
  fullName: __t.string(),
  email: __t.string(),
  isAdmin: __t.bool(),
});
export type UserProfile = __Infer<typeof UserProfile>;

